import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { SessionProvider } from "next-auth/react";

import TopNav from "./_components/topnav";

export const metadata: Metadata = {
  title: "My Job Application Tracker",
  description: "Generated by create-t3-app for funsies.",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-slate-900 text-white">
        <SessionProvider>
          <TopNav></TopNav>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
