import "~/styles/globals.css";

import React from "react";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { auth } from "~/server/auth";

import TopNav from "./_components/topnav";
import AppSidebar from "./_components/appsidebar";

import { Toaster } from "~/components/ui/sonner";
import { SidebarInset, SidebarProvider } from "~/components/ui/sidebar";

export const metadata: Metadata = {
  title: "My Job Application Tracker",
  description: "Generated by create-t3-app for funsies.",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode; modal: React.ReactNode }>) {
  const session = await auth();

  const accesslevel = session ? session.user?.accessLevel : "";

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <SidebarProvider>
          <AppSidebar variant="inset" accesslevel={accesslevel} />
          <SidebarInset>
            <TopNav session={session}></TopNav>
            <main className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden bg-slate-100">
              {children}
              {modal}
              <div id="modal-root"></div>
            </main>
            <Toaster />
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
